# Generated by Django 3.2.12 on 2022-04-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('due_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
