# Generated by Django 3.2.12 on 2022-04-13 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_character_defaultcharacter_defaultexit_defaultobject_defaultroom_object'),
        ('quest', '0002_alter_quest_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='author',
            field=models.ForeignKey(default=1, limit_choices_to={'typeclass': 'typeclasses.characters.Character'}, on_delete=django.db.models.deletion.DO_NOTHING, to='objects.objectdb'),
            preserve_default=False,
        ),
    ]
