# Generated by Django 3.2.12 on 2022-04-13 23:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0012_alter_quest_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='due_date',
            field=models.DateField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 4, 13))]),
        ),
    ]
