# Generated by Django 3.2.13 on 2022-04-22 21:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_character_defaultcharacter_defaultexit_defaultobject_defaultroom_object'),
        ('quest', '0013_alter_quest_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='hero',
            field=models.ManyToManyField(blank=True, limit_choices_to={'db_typeclass_path': 'typeclasses.characters.Character'}, to='objects.ObjectDB'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='author',
            field=models.ForeignKey(default=1, limit_choices_to={'db_typeclass_path': 'typeclasses.characters.Character'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='objects.objectdb'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='due_date',
            field=models.DateField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.date(2022, 4, 22))]),
        ),
    ]
